import source.ml.trainer.DeepPhysTrainer
import source.ml.trainer.DiffusionPhysTrainer
import source.ml.trainer.FactorizePhysTrainer
import source.ml.trainer.iBVPNetTrainer
import source.ml.trainer.TSCANTrainer
import source.ml.trainer.PhysNetTrainer
import source.ml.trainer.PhysNetTempTrainer
import source.ml.trainer.PhysNetIMUTrainer
import source.ml.trainer.PhysNetNewTrainer
import source.ml.trainer.PhysNetNewDiffusionTrainer
import source.ml.trainer.PhysNetNewIMUTrainer
import source.ml.trainer.PhysNetNewIMUCATrainer
import source.ml.trainer.PhysNetNewIMUCADiffusionTrainer
import source.ml.trainer.PhysMambaTrainer
import source.ml.trainer.PhysFormerTrainer
import source.ml.trainer.PhysFormerDiffusionTrainer
import source.ml.trainer.RhythmFormerTrainer
import source.ml.trainer.VQVAETrainer
import source.ml.trainer.VQVAEIMUTrainer
import source.ml.trainer.ContrastPhysPlusTrainer
import source.ml.trainer.RhythmMambaTrainer
import source.ml.trainer.VRPMSTrainer

