# Configurations for general of video and bio-signals of egoPPG dataset

# General parameters
dir_preprocessed: '/local/home/bjbraun/Datasets/PreprocessedData/UBFC_rPPG/DATASET_2'
fs: 30

# Preprocessing parameters for ML
h: 72                       # Number of rows of the preprocessed frames
w: 72                      # Number of columns of the preprocessed frames
clip_length_old: 256
input_name: 'face'

# Extended preprocessing parameters
video_types: ['Raw']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
label_type: 'Raw'  # Raw, Standardized, Diff, DiffStandardized
downsampling: 1
upsampling: 1
clip_length_new: 256