# Configurations for general of video and bio-signals of egoPPG dataset

# General parameters
dir_preprocessed: '/local/home/bjbraun/Datasets/PreprocessedData/PURE'
fs: 30

# Preprocessing parameters for ML
h: 48                       # Number of rows of the preprocessed frames
w: 128                      # Number of columns of the preprocessed frames
clip_length_old: 128
input_name: 'et'

# Extended preprocessing parameters
video_types: ['DiffStandardized']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
label_type: 'DiffStandardized'  # Raw, Standardized, Diff, DiffStandardized
downsampling: 1
upsampling: 1
clip_length_new: 128