# Configurations for general of video and bio-signals of egoPPG dataset

# General parameters
original_data_path: '/local/home/bjbraun/Datasets/OriginalData/UBFC_rPPG/DATASET_2'
preprocessed_data_path: '/local/home/bjbraun/Datasets/PreprocessedData/UBFC_rPPG/DATASET_2'
landmark_model_path: '/local/home/bjbraun/Projects/egoPPG/data/face_landmarker.task' # Mediapipe face landmark detection
fs: 30

# Preprocessing parameters for ML
h: 72                       # Number of rows of the preprocessed frames
w: 72                      # Number of columns of the preprocessed frames
clip_lengths: [256]
input_name: 'face'

crop_face: True
dynamic_detection: True
detection_length: 32
face_detect: True
larger_box_size: 1.0  # set dynamic detection to False if set to facial region
large_face_box: True
do_chunk: True