# Configurations for video signals of EgoExo4D dataset

# General parameters
original_data_path: '/local/data/bjbraun/Datasets/OriginalData/EgoExo4D'
preprocessed_data_path: '/local/data/bjbraun/Datasets/PreprocessedData/EgoExo4D'
fs_all: {'et': 10, 'rgb': 30, 'aria_imu_right': 1000}

# Preprocessing parameters for ML
h: 48                       # Number of rows of the preprocessed frames
w: 128                      # Number of columns of the preprocessed frames
clip_length: 128
video_types: ['DiffStandardized']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
label_type: 'DiffStandardized'  # Raw, Standardized, Diff, DiffStandardized
downsampling: 1
upsampling: 3

exclusion_list: [
  'sfu_basketball_04_38', 'sfu_basketball_10_28', 'iiith_cooking_56_2', 'uniandes_dance_016_46',
  'sfu_basketball_01_32', 'sfu_basketball_08_40', 'uniandes_bouldering_026_37',
  'uniandes_bouldering_029_76', 'uniandes_bouldering_032_56', 'sfu_basketball_05_18', 'uniandes_bouldering_036_49',
  'uniandes_bouldering_027_28', 'uniandes_bouldering_027_51', 'uniandes_bouldering_026_94',
  'uniandes_bouldering_035_101', 'uniandes_bouldering_027_25', 'uniandes_bouldering_027_65',
  'uniandes_bouldering_029_74', 'uniandes_bouldering_027_55', 'uniandes_bouldering_036_39',
  'uniandes_bouldering_027_80', 'uniandes_bouldering_023_69', 'uniandes_bouldering_023_72'
]
