# Configurations for general of video and bio-signals of egoPPG dataset

# Overall parameters
dir_preprocessed: '/data/bjbraun/Datasets/PreprocessedData/EgoExo4D'    # Path to where the preprocessed data should be saved
fs_all: {'et': 10, 'rgb': 30, 'aria_imu_left': 800, 'aria_imu_right': 1000}

# First preprocessing step parameters
h: 48                       # Number of rows of the preprocessed frames
w: 128                      # Number of columns of the preprocessed frames
clip_length_old: 32

# Extended preprocessing parameters
video_types: ['DiffStandardized']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
label_type: 'DiffStandardized'  # Raw, Standardized, Diff, DiffStandardized
downsampling: 1
upsampling: 3
clip_length_new: 128