# Configurations for general of video and bio-signals of egoPPG dataset

# General parameters
original_data_path: '/local/home/bjbraun/Datasets/OriginalData/mini_MMPD'
preprocessed_data_path: '/local/home/bjbraun/Datasets/PreprocessedData/mini_MMPD'
landmark_model_path: '/local/home/bjbraun/Projects/egoPPG/data/face_landmarker.task' # Mediapipe face landmark detection
fs: 30

# Preprocessing parameters for ML
h: 48                       # Number of rows of the preprocessed frames
w: 128                      # Number of columns of the preprocessed frames
clip_lengths: [128]
input_name: 'et'

crop_face: True
dynamic_detection: True
detection_length: 16
face_detect: True
larger_box_size: 1.0  # set dynamic detection to False if set to facial region
large_face_box: True
do_chunk: True