BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
INPUT_SIGNALS: ['et']  # face, hand: can be one or multiple depending on model
LABEL_SIGNALS: ["ppg_nose"]  # ppg_nose, ppg_ear, sys, dia, hr: can be one or multiple depending on model
INPUT_SIGNALS_TEST: ['et']  # face, hand: can be one or multiple depending on model
LABEL_SIGNALS_TEST: ["ppg_nose"]  # ppg_nose, ppg_ear, sys, dia, hr: can be one or multiple depending on model
TASKS_TO_USE: []
LABEL_VALID: 0  # index of which label of LABEL_SIGNALS to use for validation
NAME_EXTENSION: ""  # optional, just to add some extra information to the name
SPLIT_METHOD: "cross_dataset"  # loso or kfold
K_FOLD_SPLITS: 5  # if k_fold is used, specify number of splits for k_fold
DEVICE: cuda:4
NUM_OF_GPU_TRAIN: 1

TRAIN:
  BATCH_SIZE: 4  # how many files per batch to load!
  EPOCHS: 30
  LR: 9e-4  # 9e-3
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: egoppg  # egoppg, egoexo4d
    DATA_FORMAT: NCDHW
    CACHED_PATH: "/Datasets/PreprocessedData/egoPPG/Data_ML"  # where the preprocessed data is saved, relative to the DATA_PATH
    PREPROCESS:
      DATA_TYPE: ['DiffStandardized']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
      LABEL_TYPE: 'DiffStandardized'   # Raw, Standardized, Diff, DiffStandardized
      CHUNK_LENGTH_OLD: 128
      CHUNK_LENGTH: 128
      DOWNSAMPLE: 1
      UPSAMPLE: 3
      RESIZE:
        H: 48
        W: 128

TEST:
  USE_LAST_EPOCH: False                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: egoexo4d  # egoppg, egoexo4d
    DATA_FORMAT: NCDHW
    CACHED_PATH: "/Datasets/PreprocessedData/EgoExo4D/Data_ML"  # where the preprocessed data is saved, relative to the DATA_PATH
    PREPROCESS:
      DATA_TYPE: ['DiffStandardized']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
      LABEL_TYPE: 'DiffStandardized'   # Raw, Standardized, Diff, DiffStandardized
      CHUNK_LENGTH_OLD: 32
      CHUNK_LENGTH: 128
      DOWNSAMPLE: 1
      UPSAMPLE: 3
      RESIZE:
        H: 48
        W: 128

DATA_PATH: "/local/home/bjbraun"  # where the big data is saved (DATA_PATH and FILE_PATH could be the same depending on server)
FILE_PATH: "/local/home/bjbraun"  # folder for smaller files of the projects
LOG:
  PATH_TRAINING: "/Projects/EgoExo4D/runs/training"  # where the training logs are saved, relative to the FILE_PATH
  PATH_TESTING: "/Projects/EgoExo4D/runs/testing"    # where the testing logs are saved, relative to the FILE_PATH
MODEL:
  DROP_RATE: 0.1
  NAME: FactorizePhys
  FactorizePhys:
    CHANNELS: 1
    FRAME_NUM: 128
    MD_FSAM: True
    MD_TYPE: "NMF"
    MD_R: 1
    MD_S: 1
    MD_STEPS: 4
    MD_RESIDUAL: True
    MD_INFERENCE: True
  PATH_MODEL: '/Projects/egoPPG/PreTrainedModels'  # where the pre-trained models are saved, relative to the DATA_PATH
INFERENCE:
  USE_BEST_EPOCH: True
  NO_LABELS: True
  BATCH_SIZE: 4
  EVALUATION_METHOD: "Peak_Detection"        # "FFT" or "Peak_Detection" (for rPPG)
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True     # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 60               # In seconds (16)
  MODEL_PATH: "Epoch1000.pth"  # TRAIN needs to be adjusted to where model was trained from which is inferred

# Setup for 45.29 (ego + hr)
# 0.6 - 3.0, best epoch, 60 sec