BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
INPUT_SIGNALS: ['face']  # face, hand: can be one or multiple depending on model
LABEL_SIGNALS: ["ppg"]  # ppg_nose, ppg_ear, sys, dia, hr, eda_raw, eda_filtered, eda_tonic: can be one or multiple depending on model
TASKS_TO_USE: []
LABEL_VALID: 0  # index of which label of LABEL_SIGNALS to use for validation
NAME_EXTENSION: "full_loss_valid_notransform_nolabelhiding"  # optional, just to add some extra information to the name
SPLIT_METHOD: "kfold"  # loso or kfold
K_FOLD_SPLITS: 5  # if k_fold is used, specify number of splits for k_fold
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1

TRAIN:
  BATCH_SIZE: 1  # how many files per batch to load!
  EPOCHS: 30
  LR: 1e-5  # 9e-3
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: ubfc_rppg  # egoppg
    DATA_FORMAT: NCDHW
    CACHED_PATH: "/Datasets/PreprocessedData/UBFC_rPPG/DATASET_2/Data_ML"  # where the preprocessed data is saved, relative to the DATA_PATH
    PREPROCESS:
      DATA_TYPE: ['Raw']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
      LABEL_TYPE: "Raw"   # Raw, Standardized, Diff, DiffStandardized
      CHUNK_LENGTH_OLD: 128
      CHUNK_LENGTH: 128
      DOWNSAMPLE: 1
      UPSAMPLE: 1
      RESIZE:
        H: 72
        W: 72

TEST:
  USE_LAST_EPOCH: False                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: ubfc_rppg  # egoppg
    DATA_FORMAT: NCDHW
    CACHED_PATH: "/Datasets/PreprocessedData/UBFC_rPPG/DATASET_2/Data_ML"  # where the preprocessed data is saved, relative to the DATA_PATH
    PREPROCESS:
      DATA_TYPE: ['Raw']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
      LABEL_TYPE: "Raw"   # Raw, Standardized, Diff, DiffStandardized
      CHUNK_LENGTH_OLD: 128
      CHUNK_LENGTH: 128
      DOWNSAMPLE: 1
      UPSAMPLE: 1
      RESIZE:
        H: 72
        W: 72

DATA_PATH: "/local/home/bjbraun"  # where the big data is saved (DATA_PATH and FILE_PATH could be the same depending on server)
FILE_PATH: "/local/home/bjbraun"  # folder for smaller files of the projects
LOG:
  PATH_TRAINING: "/Projects/egoPPG/runs/training"  # where the training logs are saved, relative to the FILE_PATH
  PATH_TESTING: "/Projects/egoPPG/runs/testing"    # where the testing logs are saved, relative to the FILE_PATH
MODEL:
  NAME: ContrastPhysPlus
  PATH_MODEL: '/Projects/egoPPG/PreTrainedModels'  # where the pre-trained models are saved, relative to the DATA_PATH
INFERENCE:
  USE_BEST_EPOCH: True
  BATCH_SIZE: 1
  EVALUATION_METHOD: "Peak_Detection"        # "FFT" or "Peak_Detection" (for rPPG)
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True     # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 60               # In seconds
  MODEL_PATH: "EpochXXX.pth"  # TRAIN needs to be adjusted to where model was trained from which is inferred