# Configurations for general of video and bio-signals of egoPPG dataset

# Overall parameters
dir_preprocessed: '/data/bjbraun/Datasets/PreprocessedData/egoPPG'    # Path to where the preprocessed data should be saved
fs_all: {'et': 30, 'rgb': 15, 'aria_imu_left': 800, 'aria_imu_right': 1000, 'ms_imu': 64, 'ms_ecg': 1024,
       'shimmer': 256, 'md': 128}

# First preprocessing step parameters
h: 48                       # Number of rows of the preprocessed frames
w: 128                      # Number of columns of the preprocessed frames
clip_length_old: 128

# Extended preprocessing parameters
video_types: ['DiffStandardized']  # Raw, Standardized, Diff, DiffStandardized, DiffStandardizedExtended
label_type: 'DiffStandardized'  # Raw, Standardized, Diff, DiffStandardized
downsampling: 1
upsampling: 1
clip_length_new: 128